version: '3'
services:
  
  app_comp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    links:
      - my_db
    depends_on:
      my_db:
        condition: service_healthy 
    environment:
      - MONGO_PASSWORD=golan123
      - MONGO_URI=mongodb+srv://admin:${MONGO_PASSWORD}@cluster0.ht6glhz.mongodb.net/test


  my_db:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: golan123
      MONGODB_DATABASE: global
    ports:
      - "27017:27017" 
    volumes:
      - data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval","db.runCommand({ping:1}).ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    ports:
      - "8090:80"
      - "433:433"
    volumes:
      - ./config/nginx.conf:/nginx/nginx.conf 

    depends_on:
      - app_comp


volumes:
  data:
    driver: local

